name: File Integrity Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Necessary Tools
      - name: Install Necessary Tools
        run: |
          # Update package lists
          sudo apt-get update
          
          # Install Tidy for HTML validation
          sudo apt-get install -y tidy
          
          # Install Node.js and npm (required for CSSLint and ESLint)
          sudo apt-get install -y nodejs npm
          
          # Install CSSLint globally
          sudo npm install -g csslint
          
          # Install ESLint globally
          sudo npm install -g eslint

      # Step 3: Check index.html existence and syntax
      - name: Check index.html existence and syntax
        run: |
          if [ -f templates/index.html ]; then
            echo "index.html exists."
            tidy -qe templates/index.html
          else
            echo "index.html is missing!"
            exit 1
          fi

      # Step 4: Check style.css existence and syntax
      - name: Check style.css existence and syntax
        run: |
          if [ -f static/style.css ]; then
            echo "style.css exists."
            csslint static/style.css
          else
            echo "style.css is missing!"
            exit 1
          fi

      # Step 5: Check script.js existence and syntax
      - name: Check script.js existence and syntax
        run: |
          if [ -f static/script.js ]; then
            echo "script.js exists."
            eslint static/script.js
          else
            echo "script.js is missing!"
            exit 1
          fi
